# Generated by Django 5.0.3 on 2024-05-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='cover_url',
        ),
    ]
