# Generated by Django 5.0.7 on 2024-07-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmenthistory',
            old_name='description',
            new_name='diagnosis',
        ),
    ]
