# Generated by Django 5.0.7 on 2024-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_billing_prescription_billing_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
