# Generated by Django 5.0.7 on 2024-07-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='diagnoses',
            new_name='diagnosis',
        ),
    ]
