# Generated by Django 5.0.4 on 2024-06-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0002_destination_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='dest_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_images/highlights')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination_app.destination')),
            ],
        ),
    ]
