# Generated by Django 5.0.4 on 2024-06-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0003_dest_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest_images',
            old_name='image',
            new_name='images',
        ),
    ]
