# Generated by Django 5.0.4 on 2024-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0004_rename_image_dest_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destination_images/'),
        ),
    ]
