# Generated by Django 5.0.3 on 2024-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
