# Generated by Django 5.0.3 on 2024-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_projectimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_pdfs/'),
        ),
    ]
