# Generated by Django 5.0.3 on 2024-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_portfolio_portfolio_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_pdf',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificate_pdfs/'),
        ),
    ]
