# Generated by Django 5.0.3 on 2024-06-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_portfolio_certificate_pdf_certificatefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='education',
            field=models.TextField(blank=True),
        ),
    ]
