# Generated by Django 5.0.3 on 2024-06-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_portfolio_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='custom_content',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
