# Generated by Django 5.0.3 on 2024-06-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_portfolio_custom_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_value', models.TextField(blank=True)),
                ('field_image', models.ImageField(blank=True, null=True, upload_to='custom_field_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.portfolio')),
            ],
        ),
    ]
